services:
  app:
    image: webdevops/php-nginx:8.3
    container_name: helpdesk_app
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    volumes:
      - ./backend:/app
    ports:
      - "8000:80"
    depends_on:
      - postgres

  frontend:
    image: node:20
    container_name: helpdesk_frontend
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  postgres:
    image: postgres:17
    container_name: helpdesk_postgres
    restart: always
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: